#security.jwt:
#  token:
#    expiration: 600000
#    secret-key: secret-key-for-encryption
#    roles-key: roles
#    header-name: Authorization
#    password-strength: 7
#    prefix: Bearer
#  roles:
#    -
#      name: ROLE_ADMIN
#      description: Super Admin
#    -
#      name: ROLE_USER
#      description: Simple User
#  users:
#    -
#      username: root
#      password: root
#      roles:
#        - ROLE_ADMIN
#        - ROLE_USER

